services:
  discord-clockify-bot:
    container_name: discord-clockify-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
